### ISSUE TITLE
Factory falls down w "out of gas state" while deploying

### ISSUE THREAD

**Issue by quasisamurai** [sonm-io/The-Factory#22]
The main problem of current Factory contract is
```
Error: VM Exception while processing transaction: out of gas
```

Thus, through trial and error I found two functions commenting **one of which** leads to this result

```
   function createHub(bool _privat) public returns (address) {
        address _hubowner = msg.sender;
        address hubProfile = createH(_hubowner,_privat);
        Profiles[_hubowner] = hubProfile;
        types[hubProfile] = TypeW.Hub;
        privat[hubProfile] = _privat;
        LogCreate(hubProfile, _hubowner);
    }

  function createMiner() public returns (address) {
        address _minowner = msg.sender;
        address minProfile = createM(_minowner);
        Profiles[_minowner] = minProfile;
        types[_minowner] = TypeW.Miner;
        LogCreate(minProfile, _minowner);
    }
```

Obviosly, there is no infinite cycles. So hope you know how to solve this problem.

**Comment by quasisamurai** [comment]
when I  run
`truffle migrate`

i get 



> Running migration: 1_initial_migration.js
>   Deploying Migrations...
>   ... 0x1b99519b95e235d4a3166b2d42345b859816708799b260d198d2df92893027a2
>   Migrations: 0xf883a9b439c6dc5a89972a26630536b307b218dd
> Saving successful migration to network...
>   ... 0x154d9808afd1ac402f769f59d8c0b6e6969ef2e450737a14582d3a3c97c17003
> Saving artifacts...
> Running migration: 2_deploy_contracts.js
>   Deploying SDT...
>   ... 0x5ebcbe3125e448c0ca5d89085d8c61b5abb35faa16459e869f92d0edd17714cf
>   SDT: 0x63c953bcadf7738660e24d025f0efc9eeb7b4854
>   Deploying Factory...
>   ... undefined
> Error encountered, bailing. Network state unknown. Review successful transactions manually.
> **Error: VM Exception while processing transaction: out of gas**
>     at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
>     at /usr/lib/node_modules/truffle/build/cli.bundled.js:224765:36
>     at /usr/lib/node_modules/truffle/build/cli.bundled.js:66971:11
>     at /usr/lib/node_modules/truffle/build/cli.bundled.js:208348:9
>     at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
>     at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
>     at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
>     at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
>     at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:67535:24)
>     at emitNone (events.js:91:20)
> 

also testrpc log (only for factory)


> Transaction: 0x20abbf415c71b7c3198ec719e9c26ab785ef2ec760d99cb332a969d3815f7162
>   Contract created: 0xf81e2933ee1d5a82acf28b34757da41ad3ae113c
>   **Gas usage: 3000000**
>   Block Number: 4
>   Block Time: Wed Aug 16 2017 19:12:16 GMT+0300 (MSK)
>   Runtime Error: out of gas

**Comment by JackBekket** [comment]
Could you try ```truffle migrate --reset ```?

**Comment by quasisamurai** [comment]
I always run `--reset` option while deploying.  Testrpc, solc and truffle core updated to last versons. Look, is anything allright with my varaiant of `2_deploy_modules.js`?

**Comment by JackBekket** [comment]
Not really, but I will try to fix it myself

**Comment by JackBekket** [comment]
Problem fixed. You have bad npm installation, pull recent commit, type ```npm install``` and then ```truffle migrate --reset ```.

**Comment by JackBekket** [comment]
And close this issue please

**Comment by quasisamurai** [comment]
Done.
