### ISSUE TITLE
Clean&Organize

### ISSUE THREAD

**Issue by JackBekket** [sonm-io/The-Factory#47]
Tasks:
1. delete branch ``` remove_miner_logic``` cause this branch was succesfully merged and we don't need it anymore. Some of developers think that it's branch the last one and tries to commit there, therefore it cause some chaos mess in process of work.  I can't delete it myself, so I need to delete it from those, who create it.
2. Make PR from debug to upstream (0.2) to show everyone latest changes in architecture. 
3. All future PR should process as:
a.) fork from ```debug``` branch in the **organization** repo, not personal one. It need to see all works across repo and aganist misscomunication when two developers are working on the same future. 
b.) make PR to ```debug``` with definition what has been done
c.) make sure to clean merged branches after work and also make sure that you told your superviser (or just Manaev) that work has been done. (He must notice it in Jira)
d.) we making PR to 0.2 from debug periodicaly untill deployment into testnetwork. then I guess we change organising rules somehow. Probably master will contain only deployed versions, or it will be versions that just have been integrated  - will discuss it later

**Comment by Sokel** [comment]
1) it may be using `master` instead of `v0.2` as default branch?
2) it may be great to enable `review required` and `ci require` option for merging pull requests.
