### ISSUE TITLE
Rating updating

### ISSUE THREAD

**Issue by emanaev** [sonm-io/The-Factory#51]
Ensure, that the function to calculate rating is called when applicable: to increase the rating when the deal is ok, to decrease rating when there are uncollborated appeals

**Comment by JackBekket** [comment]
Like this: https://github.com/sonm-io/The-Factory/blob/debug/contracts/Profile.sol#L156

This issue must be worked and closed **after** https://github.com/sonm-io/The-Factory/issues/55

**Comment by emanaev** [comment]
We haven't got precise understanding of the rating algorithm. So I would postpone this issue to exclude coding-merging-deleting cycle.

**Comment by emanaev** [comment]
We haven't got precise understanding of the rating algorithm. So I would postpone this issue

**Comment by JackBekket** [comment]
will be transformed with new conditions, task cancelled

**Comment by JackBekket** [comment]
Transformed into https://github.com/sonm-io/The-Factory/issues/62
