### ISSUE TITLE
Attach profile to network

### ISSUE THREAD

**Issue by emanaev** [sonm-io/The-Factory#53]
Payout period is set while profile is registering in the network. Essentially it's a time period for profile couldnot leave the network. Administration control and punishment can be processed only when profile is in Registered status.

The function UpdateRate must be implemented, so that profile can send new rating to the Network without unregistration process. The function should also send collected fees to DAO.

**Comment by JackBekket** [comment]
Particially transformed into https://github.com/sonm-io/The-Factory/issues/62
