### ISSUE TITLE
Rate Variables

### ISSUE THREAD

**Issue by JackBekket** [sonm-io/The-Factory#55]
Each profile contract should have next variables - 
1. sum of costs in positive cases
2. sum of costs in negative cases
3. how much was succesfull deals
4. how much was unsuccesfull deals.
 + events which we has discussed in friday.

**Comment by JackBekket** [comment]
After this is done please check https://github.com/sonm-io/The-Factory/issues/51

**Comment by quasisamurai** [comment]
Okay, i'll do _dat_ task.

**Comment by emanaev** [comment]
We haven't got precise understanding of the rating algorithm. So I would postpone this issue

**Comment by quasisamurai** [comment]
I have already did this, but I'm not for sure that this variables is exactly we need. As Eugeny said, we haven't got clear idea how should ratings work. So this kind of tasks could be completed in less than 2 hours. My opinion - we need to wait, not to rush this part.

**Comment by JackBekket** [comment]
will be transformed with new conditions, task cancelled

**Comment by JackBekket** [comment]
Transform into https://github.com/sonm-io/The-Factory/issues/62
