### ISSUE TITLE
Conceptual: PAUG

### ISSUE THREAD

**Issue by JackBekket** [sonm-io/The-Factory#56]
# Pay As You Go

Feature allow hub to take payments from deal in depend of how much time was spent on it, also known as "Pay As You Go". 

We still have some conceptual conflicts besides that feature and 'deal time extension'.

Below is description what we need to do in any case:

Описание работы функции:
1.  ``` (nowTime - paid time) *pricePerHour = withdr amount ```
2. Размораживаем wthdr из LockedFunds с контракта пользователя (locked funds в сущности сделки НЕ меняем). Таким образом хаб может сразу пользоваться размороженными средствами через перегруженный трансфер, при этом платя нам комиссию за переводы
3. Записываем время выполнения функции в paid time 
4. Когда сделка успешно завершается, дергаем эту функцию.
5. Когда сделка завершается конфликтом, то сначала вызываем эту функцию, получаем wthdr amount и переводим остаток от сделки покупателю (в зависимости от конкретных условий расторжения, см примечания Игоря)

Доп. прим - когда работаем со временем, то берем
 now * 1 hour 
.  now и обозначения времени - служебные переменные, умножение на 1 служебную переменную приводит тип времени к нужному нам формату. Следите за тем, что бы дни не умножались на часы и наоборот.

**Comment by JackBekket** [comment]
__paid time__ - should be record in deals struct by the way

**Comment by JackBekket** [comment]
Also connected with https://github.com/sonm-io/The-Factory/issues/41

**Comment by quasisamurai** [comment]
Got it.

**Comment by emanaev** [comment]
I suggest postponing this issue until the team clearly understands which deal types we are going to implement, and how it should work

**Comment by quasisamurai** [comment]
There is one nuance. As actual architecture demands, we do not completly understand  PAUG conceps in cause of use cases. Should I do this task anyway?

**Comment by Sokel** [comment]
@quasisamurai you may try to do 1 and 3 point of this.
In other we need some experienced work above transfer with commission.

**Comment by JackBekket** [comment]
Don't postpone, do and push this issue to debug,  extendability of deals we can discuss in SIP I wrote yesterday

**Comment by quasisamurai** [comment]
#59
